
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:8080
  data:
    mongodb:
      uri: ${mongoUri}
      database: auth
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${emailUsername}
    password: ${password}
    properties:
      mail:
        smtp:
          auth: true
          debug: true
          starttls:
            enable: true

baseUrl: ${baseUrl}